apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-presupuesto-mineco
  namespace: mineco
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: pv-presupuesto-mineco
