apiVersion: v1
kind: ConfigMap
metadata:
  name: presupuesto-frontend-nginx-config
  namespace: mineco
data:
  nginx.conf: |
    user nginx;

    worker_processes auto;

    events {
      worker_connections 1024;
    }

    http {
      include mime.types;
      default_type application/octet-stream;

      gzip on;
      gzip_types text/plain text/css application/json application/javascript application/xml application/xml+rss text/javascript image/svg+xml font/woff2;
      gzip_min_length 1000;
      gzip_proxied any;
      gzip_disable "msie6";

      server {
        listen 80;
        return 301 https://presupuesto.mineco.gob.gt$request_uri;
      }

      server {
        listen 443 ssl;
        server_name presupuesto.mineco.gob.gt;

        ssl_certificate     /etc/ssl/private/mineco.crt;
        ssl_certificate_key /etc/ssl/private/mineco.key;

        root /var/www/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location ~ ^/api/ {
            root /var/www/html;

            fastcgi_pass presupuesto-backend-service:9000;
            fastcgi_index index.php;

            include fastcgi.conf;

            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
            fastcgi_param DOCUMENT_ROOT /var/www/html/public;
        }

        location ~ /\.ht {
          deny all;
        }

        location ~ /\.(?!well-known).* {
          deny all;
        }

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
          expires 1y;
          add_header Cache-Control "public, max-age=31536000, immutable";
        }
      }
    }
