apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vaultwarden
  namespace: namespace
  labels:
    name: pv-vaultwarden
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 128.5.8.222
    path: "/home/deployment/vaultwarden"
