apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vaultwarden
  namespace: namespace
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: pv-vaultwarden
