apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: namespace
spec:
  type: LoadBalancer
  externalIPs:
    - 128.5.4.106
  selector:
    app: vaultwarden
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
