apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-transporte-mineco
  namespace: mineco
  labels:
    name: pv-transporte-mineco
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 128.5.8.222
    path: "/home/deployment/transporte"
